import { AssessmentResult } from "../types";

export function downloadSecurityReport(assessment: AssessmentResult) {
  const content = `================================================================================
                    TUNNELSCOPE SECURITY ASSESSMENT REPORT
                          [DEMO ASSESSMENT SUMMARY]
================================================================================

Target Dataset     : ${assessment.datasetName}
Records Analyzed   : ${assessment.rowCount.toLocaleString()}
Columns Evaluated  : ${assessment.columnCount}
Analysis Timestamp : ${assessment.analyzedAt}
Overall Score      : ${assessment.overallScore} / 100 (${assessment.postureLabel})

--------------------------------------------------------------------------------
1. EXECUTIVE SUMMARY
--------------------------------------------------------------------------------
${assessment.summaryText}

DISCLAIMER:
This assessment reflects simulated/demonstration metrics generated by TunnelScope
for workflow evaluation purposes. Not certified for regulatory compliance.

--------------------------------------------------------------------------------
2. SECURITY SCORE BREAKDOWN
--------------------------------------------------------------------------------
- Encryption Strength   : ${assessment.breakdown.encryption.score}/100 [${assessment.breakdown.encryption.status}]
  Details: ${assessment.breakdown.encryption.details}

- Key Exchange Policy   : ${assessment.breakdown.keyExchange.score}/100 [${assessment.breakdown.keyExchange.status}]
  Details: ${assessment.breakdown.keyExchange.details}

- Tunnel Encapsulation  : ${assessment.breakdown.tunnelSecurity.score}/100 [${assessment.breakdown.tunnelSecurity.status}]
  Details: ${assessment.breakdown.tunnelSecurity.details}

- Quantum Readiness     : ${assessment.breakdown.quantumReadiness.score}/100 [${assessment.breakdown.quantumReadiness.status}]
  Details: ${assessment.breakdown.quantumReadiness.details}

- Cyber Resilience      : ${assessment.breakdown.cyberResilience.score}/100 [${assessment.breakdown.cyberResilience.status}]
  Details: ${assessment.breakdown.cyberResilience.details}

--------------------------------------------------------------------------------
3. DETECTED TUNNEL & CRYPTOGRAPHIC SPECIFICATIONS
--------------------------------------------------------------------------------
- Tunnel Architecture   : ${assessment.tunnelSpecs.tunnelType}
- Transport Layer       : ${assessment.tunnelSpecs.transportProtocol}
- Symmetric Cipher      : ${assessment.tunnelSpecs.cipherSuite}
- Key Exchange Method   : ${assessment.tunnelSpecs.keyExchangeMethod}
- Forward Secrecy (PFS) : ${assessment.tunnelSpecs.pfsEnabled ? "Enabled" : "Disabled"}
- Integrity / Digest    : ${assessment.tunnelSpecs.authDigest}
- Configured MTU        : ${assessment.tunnelSpecs.mtuSize} bytes

--------------------------------------------------------------------------------
4. CYBER ASSESSMENT DIMENSIONS
--------------------------------------------------------------------------------
${assessment.cyberDimensions
  .map(
    (dim) =>
      `• ${dim.name.padEnd(26)} : ${dim.score}/100 - ${dim.description}`
  )
  .join("\n")}

--------------------------------------------------------------------------------
5. PRIORITIZED SECURITY RECOMMENDATIONS (DEMO)
--------------------------------------------------------------------------------
${assessment.recommendations
  .map(
    (rec) =>
      `[${rec.id}] ${rec.title} (${rec.priority} Priority)\n` +
      `  Action: ${rec.description}\n`
  )
  .join("\n")}

================================================================================
End of TunnelScope Assessment. Report ID: TS-RPT-${Math.floor(
    Math.random() * 89999 + 10000
  )}
================================================================================
`;

  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const safeName = assessment.datasetName.replace(/[^a-zA-Z0-9_-]/g, "_");
  a.download = `TunnelScope_Assessment_${safeName}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
